plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.challenge'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.hibernate.orm:hibernate-community-dialects'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
	runtimeOnly 'org.xerial:sqlite-jdbc'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.register('buildFrontend', Exec) {
	workingDir 'frontend'
	if (System.getProperty('os.name').toLowerCase().contains('windows')) {
		commandLine 'cmd', '/c', 'npm run build'
	} else {
		commandLine 'npm', 'run', 'build'
	}
}

tasks.register('copyFrontend', Copy) {
	dependsOn 'buildFrontend'
	from 'frontend/dist'
	into 'src/main/resources/static'
}

processResources.dependsOn 'copyFrontend'

tasks.withType(JavaCompile) {
	options.encoding = 'UTF-8'
}


